name: alquran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  get: 4.6.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  just_audio: 0.9.32
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svgs/
    - assets/png/
  uses-material-design: true

